[project]
name = "opendataswiss"
version = "0.1.0"
description = ""
authors = [
    {name = "Sam Woodcock", email = "samuel.woodcock@wsl.ch"},
    {name= "Rebecca Kurup Buchholz", email = "None"}
]
dependencies = [
    "s3-bucket>=1.4.0",
    "requests==2.27.1",
]
requires-python = ">=3.9"
license = {text = "MIT"}

[tool.pdm]
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[tool.pdm.dev-dependencies]
dev = []

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
